/**
 * theme-data.js — Design Companion Theme Selector data
 *
 * Defines window.THEME_DATA with all 10 palette token sets and
 * 4 color variants (default, dark, warm, cool) for each palette.
 *
 * Injected by server.cjs as a <script> block before helper.js.
 */

window.THEME_DATA = {

  palettes: [

    // ─── Tier 1: Adoptable Systems ───────────────────────────────────────────

    {
      key: 'material',
      name: 'Material Design',
      desc: 'Bold type hierarchy, surface elevation, rounded corners',
      tier: 1,
      tokens: {
        '--color-primary':          '#6750A4',
        '--color-primary-hover':    '#4F378B',
        '--color-on-primary':       '#FFFFFF',
        '--color-bg':               '#FFFBFE',
        '--color-surface':          '#FFFFFF',
        '--color-surface-variant':  '#E7E0EC',
        '--color-border':           '#CAC4D0',
        '--color-text':             '#1C1B1F',
        '--color-text-secondary':   '#49454F',
        '--color-text-tertiary':    '#79747E',
        '--color-success':          '#386A20',
        '--color-warning':          '#7D5700',
        '--color-danger':           '#B3261E',

        '--space-xs':  '0.25rem',
        '--space-sm':  '0.5rem',
        '--space-md':  '1rem',
        '--space-lg':  '1.5rem',
        '--space-xl':  '2rem',

        '--font-family':        "'Google Sans', 'Roboto', sans-serif",
        '--font-xs':            '0.6875rem',
        '--font-sm':            '0.75rem',
        '--font-base':          '0.875rem',
        '--font-lg':            '1rem',
        '--font-xl':            '1.125rem',
        '--font-2xl':           '1.375rem',
        '--font-weight-normal': '400',
        '--font-weight-medium': '500',
        '--font-weight-bold':   '700',

        '--radius-sm':   '4px',
        '--radius-md':   '12px',
        '--radius-lg':   '16px',
        '--radius-full': '9999px',
        '--shadow-sm':   '0 1px 2px rgba(0,0,0,0.10), 0 1px 3px rgba(0,0,0,0.08)',
        '--shadow-md':   '0 1px 2px rgba(0,0,0,0.12), 0 2px 6px rgba(0,0,0,0.10)',
        '--shadow-lg':   '0 2px 6px rgba(0,0,0,0.14), 0 4px 12px rgba(0,0,0,0.12)',
      },
      variants: {
        default: {},
        dark: {
          '--color-bg':              '#1a1a1e',
          '--color-surface':         '#2d2d30',
          '--color-surface-variant': '#3a3a3f',
          '--color-border':          '#4a4a4e',
          '--color-text':            '#f0f0f2',
          '--color-text-secondary':  '#b8b8c0',
          '--color-text-tertiary':   '#80808a',
        },
        warm: {
          '--color-bg':              '#faf7f2',
          '--color-surface':         '#fffcf7',
          '--color-surface-variant': '#f0ebe2',
          '--color-border':          '#d8d0c8',
          '--color-text':            '#1C1B1F',
          '--color-text-secondary':  '#49454F',
          '--color-text-tertiary':   '#79747E',
        },
        cool: {
          '--color-bg':              '#f2f5fa',
          '--color-surface':         '#f7f9ff',
          '--color-surface-variant': '#e8ecf4',
          '--color-border':          '#c8d0dc',
          '--color-text':            '#1C1B1F',
          '--color-text-secondary':  '#49454F',
          '--color-text-tertiary':   '#79747E',
        },
        anthro: {
          '--color-bg':              '#FAF6F1',
          '--color-surface':         '#FDF9F5',
          '--color-surface-variant': '#F0E8DF',
          '--color-border':          '#D8C8B8',
          '--color-text':            '#1C1B1F',
          '--color-text-secondary':  '#49454F',
          '--color-text-tertiary':   '#79747E',
        },
        vibrant: {
          '--color-bg':              '#FFFFFF',
          '--color-surface':         '#F5F5F5',
          '--color-surface-variant': '#EEEEEE',
          '--color-border':          '#E0E0E0',
          '--color-text':            '#090909',
          '--color-text-secondary':  '#333333',
          '--color-text-tertiary':   '#777777',
        },
      },
    },

    {
      key: 'apple',
      name: 'Apple HIG',
      desc: 'Generous whitespace, subtle depth, consumer-grade polish',
      tier: 1,
      tokens: {
        '--color-primary':          '#007AFF',
        '--color-primary-hover':    '#0062CC',
        '--color-on-primary':       '#FFFFFF',
        '--color-bg':               '#F2F2F7',
        '--color-surface':          '#FFFFFF',
        '--color-surface-variant':  '#E5E5EA',
        '--color-border':           '#C6C6C8',
        '--color-text':             '#000000',
        '--color-text-secondary':   '#3C3C43',
        '--color-text-tertiary':    '#8E8E93',
        '--color-success':          '#34C759',
        '--color-warning':          '#FF9500',
        '--color-danger':           '#FF3B30',

        '--space-xs':  '0.25rem',
        '--space-sm':  '0.5rem',
        '--space-md':  '1rem',
        '--space-lg':  '1.75rem',
        '--space-xl':  '2.5rem',

        '--font-family':        "-apple-system, 'SF Pro Text', 'Helvetica Neue', sans-serif",
        '--font-xs':            '0.6875rem',
        '--font-sm':            '0.8125rem',
        '--font-base':          '0.9375rem',
        '--font-lg':            '1.0625rem',
        '--font-xl':            '1.25rem',
        '--font-2xl':           '1.5rem',
        '--font-weight-normal': '400',
        '--font-weight-medium': '500',
        '--font-weight-bold':   '600',

        '--radius-sm':   '8px',
        '--radius-md':   '12px',
        '--radius-lg':   '18px',
        '--radius-full': '9999px',
        '--shadow-sm':   '0 1px 3px rgba(0,0,0,0.08), 0 1px 2px rgba(0,0,0,0.06)',
        '--shadow-md':   '0 4px 12px rgba(0,0,0,0.10), 0 2px 4px rgba(0,0,0,0.06)',
        '--shadow-lg':   '0 8px 24px rgba(0,0,0,0.12), 0 4px 8px rgba(0,0,0,0.08)',
      },
      variants: {
        default: {},
        dark: {
          '--color-bg':              '#1a1a1e',
          '--color-surface':         '#2d2d30',
          '--color-surface-variant': '#3a3a3f',
          '--color-border':          '#4a4a4e',
          '--color-text':            '#f0f0f2',
          '--color-text-secondary':  '#b8b8c0',
          '--color-text-tertiary':   '#80808a',
        },
        warm: {
          '--color-bg':              '#faf7f2',
          '--color-surface':         '#fffcf7',
          '--color-surface-variant': '#f0ebe2',
          '--color-border':          '#d0c8c0',
          '--color-text':            '#000000',
          '--color-text-secondary':  '#3C3C43',
          '--color-text-tertiary':   '#8E8E93',
        },
        cool: {
          '--color-bg':              '#f2f5fa',
          '--color-surface':         '#f7f9ff',
          '--color-surface-variant': '#e8ecf4',
          '--color-border':          '#c0c8d8',
          '--color-text':            '#000000',
          '--color-text-secondary':  '#3C3C43',
          '--color-text-tertiary':   '#8E8E93',
        },
        anthro: {
          '--color-bg':              '#FAF6F1',
          '--color-surface':         '#FDF9F5',
          '--color-surface-variant': '#EEE4D8',
          '--color-border':          '#D4C2AE',
          '--color-text':            '#000000',
          '--color-text-secondary':  '#3C3C43',
          '--color-text-tertiary':   '#8E8E93',
        },
        vibrant: {
          '--color-bg':              '#FFFFFF',
          '--color-surface':         '#F8F8F8',
          '--color-surface-variant': '#F0F0F0',
          '--color-border':          '#DEDEDE',
          '--color-text':            '#000000',
          '--color-text-secondary':  '#2C2C2E',
          '--color-text-tertiary':   '#636366',
        },
      },
    },

    {
      key: 'tailwind',
      name: 'Tailwind / Shadcn',
      desc: 'Clean, utility-driven, modern SaaS default',
      tier: 1,
      tokens: {
        '--color-primary':          '#18181B',
        '--color-primary-hover':    '#3F3F46',
        '--color-on-primary':       '#FAFAFA',
        '--color-bg':               '#FAFAFA',
        '--color-surface':          '#FFFFFF',
        '--color-surface-variant':  '#F4F4F5',
        '--color-border':           '#E4E4E7',
        '--color-text':             '#09090B',
        '--color-text-secondary':   '#3F3F46',
        '--color-text-tertiary':    '#71717A',
        '--color-success':          '#16A34A',
        '--color-warning':          '#CA8A04',
        '--color-danger':           '#DC2626',

        '--space-xs':  '0.25rem',
        '--space-sm':  '0.5rem',
        '--space-md':  '1rem',
        '--space-lg':  '1.5rem',
        '--space-xl':  '2rem',

        '--font-family':        "'Inter', 'Geist', system-ui, sans-serif",
        '--font-family-mono':   "'Geist Mono', 'JetBrains Mono', 'Fira Code', monospace",
        '--font-xs':            '0.6875rem',
        '--font-sm':            '0.8125rem',
        '--font-base':          '0.875rem',
        '--font-lg':            '1rem',
        '--font-xl':            '1.125rem',
        '--font-2xl':           '1.375rem',
        '--font-weight-normal': '400',
        '--font-weight-medium': '500',
        '--font-weight-bold':   '600',

        '--radius-sm':   '4px',
        '--radius-md':   '6px',
        '--radius-lg':   '8px',
        '--radius-full': '9999px',
        '--shadow-sm':   '0 1px 2px rgba(0,0,0,0.05)',
        '--shadow-md':   '0 1px 3px rgba(0,0,0,0.08), 0 1px 2px rgba(0,0,0,0.04)',
        '--shadow-lg':   '0 4px 6px rgba(0,0,0,0.06), 0 2px 4px rgba(0,0,0,0.04)',
      },
      variants: {
        default: {},
        dark: {
          '--color-bg':              '#1a1a1e',
          '--color-surface':         '#2d2d30',
          '--color-surface-variant': '#3a3a3f',
          '--color-border':          '#4a4a4e',
          '--color-text':            '#f0f0f2',
          '--color-text-secondary':  '#b8b8c0',
          '--color-text-tertiary':   '#80808a',
        },
        warm: {
          '--color-bg':              '#faf7f2',
          '--color-surface':         '#fffcf7',
          '--color-surface-variant': '#f0ebe2',
          '--color-border':          '#dcdad5',
          '--color-text':            '#09090B',
          '--color-text-secondary':  '#3F3F46',
          '--color-text-tertiary':   '#71717A',
        },
        cool: {
          '--color-bg':              '#f2f5fa',
          '--color-surface':         '#f7f9ff',
          '--color-surface-variant': '#e8ecf4',
          '--color-border':          '#d8dce4',
          '--color-text':            '#09090B',
          '--color-text-secondary':  '#3F3F46',
          '--color-text-tertiary':   '#71717A',
        },
        anthro: {
          '--color-bg':              '#FAF6F1',
          '--color-surface':         '#FDF9F5',
          '--color-surface-variant': '#EFE6DA',
          '--color-border':          '#D5C5B3',
          '--color-text':            '#09090B',
          '--color-text-secondary':  '#3F3F46',
          '--color-text-tertiary':   '#71717A',
        },
        vibrant: {
          '--color-bg':              '#FAFAFA',
          '--color-surface':         '#FFFFFF',
          '--color-surface-variant': '#F4F4F5',
          '--color-border':          '#E0E0E3',
          '--color-text':            '#000000',
          '--color-text-secondary':  '#18181B',
          '--color-text-tertiary':   '#52525B',
        },
      },
    },

    {
      key: 'ant',
      name: 'Ant Design',
      desc: 'Structured, data-heavy, enterprise-grade tables and forms',
      tier: 1,
      tokens: {
        '--color-primary':          '#1677FF',
        '--color-primary-hover':    '#0958D9',
        '--color-on-primary':       '#FFFFFF',
        '--color-bg':               '#F5F5F5',
        '--color-surface':          '#FFFFFF',
        '--color-surface-variant':  '#FAFAFA',
        '--color-border':           '#D9D9D9',
        '--color-text':             '#000000D9',
        '--color-text-secondary':   '#000000A6',
        '--color-text-tertiary':    '#00000073',
        '--color-success':          '#52C41A',
        '--color-warning':          '#FAAD14',
        '--color-danger':           '#FF4D4F',

        '--space-xs':  '0.25rem',
        '--space-sm':  '0.5rem',
        '--space-md':  '0.75rem',
        '--space-lg':  '1rem',
        '--space-xl':  '1.5rem',

        '--font-family':        "-apple-system, 'PingFang SC', 'Hiragino Sans GB', 'Segoe UI', sans-serif",
        '--font-xs':            '0.625rem',
        '--font-sm':            '0.75rem',
        '--font-base':          '0.875rem',
        '--font-lg':            '1rem',
        '--font-xl':            '1.125rem',
        '--font-2xl':           '1.25rem',
        '--font-weight-normal': '400',
        '--font-weight-medium': '500',
        '--font-weight-bold':   '600',

        '--radius-sm':   '2px',
        '--radius-md':   '6px',
        '--radius-lg':   '8px',
        '--radius-full': '9999px',
        '--shadow-sm':   '0 1px 2px rgba(0,0,0,0.03), 0 1px 6px -1px rgba(0,0,0,0.02)',
        '--shadow-md':   '0 3px 6px rgba(0,0,0,0.04), 0 6px 16px rgba(0,0,0,0.04)',
        '--shadow-lg':   '0 6px 16px rgba(0,0,0,0.06), 0 12px 28px rgba(0,0,0,0.05)',
      },
      variants: {
        default: {},
        dark: {
          '--color-bg':              '#1a1a1e',
          '--color-surface':         '#2d2d30',
          '--color-surface-variant': '#3a3a3f',
          '--color-border':          '#4a4a4e',
          '--color-text':            '#f0f0f2',
          '--color-text-secondary':  '#b8b8c0',
          '--color-text-tertiary':   '#80808a',
        },
        warm: {
          '--color-bg':              '#faf7f2',
          '--color-surface':         '#fffcf7',
          '--color-surface-variant': '#f5f2ed',
          '--color-border':          '#d9d5d0',
          '--color-text':            '#000000D9',
          '--color-text-secondary':  '#000000A6',
          '--color-text-tertiary':   '#00000073',
        },
        cool: {
          '--color-bg':              '#f2f5fa',
          '--color-surface':         '#f7f9ff',
          '--color-surface-variant': '#f0f3f8',
          '--color-border':          '#d5d8e0',
          '--color-text':            '#000000D9',
          '--color-text-secondary':  '#000000A6',
          '--color-text-tertiary':   '#00000073',
        },
        anthro: {
          '--color-bg':              '#FAF6F1',
          '--color-surface':         '#FDF9F5',
          '--color-surface-variant': '#F0E6D8',
          '--color-border':          '#D4C0A8',
          '--color-text':            '#000000D9',
          '--color-text-secondary':  '#000000A6',
          '--color-text-tertiary':   '#00000073',
        },
        vibrant: {
          '--color-bg':              '#F5F5F5',
          '--color-surface':         '#FFFFFF',
          '--color-surface-variant': '#FAFAFA',
          '--color-border':          '#D9D9D9',
          '--color-text':            '#000000E8',
          '--color-text-secondary':  '#000000B0',
          '--color-text-tertiary':   '#00000080',
        },
      },
    },

    // ─── Tier 2: Personality Archetypes ──────────────────────────────────────

    {
      key: 'corporate-dense',
      name: 'Corporate Dense',
      desc: 'Compact spacing, small type, high density dashboards',
      tier: 2,
      tokens: {
        '--color-primary':          '#0052CC',
        '--color-primary-hover':    '#0747A6',
        '--color-on-primary':       '#FFFFFF',
        '--color-bg':               '#F4F5F7',
        '--color-surface':          '#FFFFFF',
        '--color-surface-variant':  '#EBECF0',
        '--color-border':           '#C1C7D0',
        '--color-text':             '#172B4D',
        '--color-text-secondary':   '#42526E',
        '--color-text-tertiary':    '#6B778C',
        '--color-success':          '#006644',
        '--color-warning':          '#FF8B00',
        '--color-danger':           '#BF2600',

        '--space-xs':  '0.125rem',
        '--space-sm':  '0.25rem',
        '--space-md':  '0.5rem',
        '--space-lg':  '0.75rem',
        '--space-xl':  '1rem',

        '--font-family':        "'Charlie Text', '-apple-system', 'Segoe UI', sans-serif",
        '--font-xs':            '0.625rem',
        '--font-sm':            '0.6875rem',
        '--font-base':          '0.8125rem',
        '--font-lg':            '0.9375rem',
        '--font-xl':            '1rem',
        '--font-2xl':           '1.125rem',
        '--font-weight-normal': '400',
        '--font-weight-medium': '500',
        '--font-weight-bold':   '600',

        '--radius-sm':   '2px',
        '--radius-md':   '3px',
        '--radius-lg':   '4px',
        '--radius-full': '9999px',
        '--shadow-sm':   '0 1px 1px rgba(9,30,66,0.13)',
        '--shadow-md':   '0 1px 3px rgba(9,30,66,0.13), 0 0 1px rgba(9,30,66,0.08)',
        '--shadow-lg':   '0 3px 6px rgba(9,30,66,0.16), 0 0 1px rgba(9,30,66,0.06)',
      },
      variants: {
        default: {},
        dark: {
          '--color-bg':              '#1a1a1e',
          '--color-surface':         '#2d2d30',
          '--color-surface-variant': '#3a3a3f',
          '--color-border':          '#4a4a4e',
          '--color-text':            '#f0f0f2',
          '--color-text-secondary':  '#b8b8c0',
          '--color-text-tertiary':   '#80808a',
        },
        warm: {
          '--color-bg':              '#faf7f2',
          '--color-surface':         '#fffcf7',
          '--color-surface-variant': '#f0ebe2',
          '--color-border':          '#c8c4bc',
          '--color-text':            '#172B4D',
          '--color-text-secondary':  '#42526E',
          '--color-text-tertiary':   '#6B778C',
        },
        cool: {
          '--color-bg':              '#f2f5fa',
          '--color-surface':         '#f7f9ff',
          '--color-surface-variant': '#e8ecf4',
          '--color-border':          '#bcc4d4',
          '--color-text':            '#172B4D',
          '--color-text-secondary':  '#42526E',
          '--color-text-tertiary':   '#6B778C',
        },
        anthro: {
          '--color-bg':              '#FAF6F1',
          '--color-surface':         '#FDF9F5',
          '--color-surface-variant': '#EDE4D8',
          '--color-border':          '#C8B8A4',
          '--color-text':            '#172B4D',
          '--color-text-secondary':  '#42526E',
          '--color-text-tertiary':   '#6B778C',
        },
        vibrant: {
          '--color-bg':              '#F4F5F7',
          '--color-surface':         '#FFFFFF',
          '--color-surface-variant': '#EBECF0',
          '--color-border':          '#B3BAC5',
          '--color-text':            '#091E42',
          '--color-text-secondary':  '#253858',
          '--color-text-tertiary':   '#5E6C84',
        },
      },
    },

    {
      key: 'clean-spacious',
      name: 'Clean & Spacious',
      desc: 'Generous whitespace, restrained palette, premium SaaS feel',
      tier: 2,
      tokens: {
        '--color-primary':          '#635BFF',
        '--color-primary-hover':    '#4F46E5',
        '--color-on-primary':       '#FFFFFF',
        '--color-bg':               '#F6F9FC',
        '--color-surface':          '#FFFFFF',
        '--color-surface-variant':  '#F0F4F8',
        '--color-border':           '#E0E6EC',
        '--color-text':             '#0A2540',
        '--color-text-secondary':   '#425466',
        '--color-text-tertiary':    '#8898AA',
        '--color-success':          '#09825D',
        '--color-warning':          '#C98A00',
        '--color-danger':           '#CD3D64',

        '--space-xs':  '0.375rem',
        '--space-sm':  '0.75rem',
        '--space-md':  '1.25rem',
        '--space-lg':  '2rem',
        '--space-xl':  '3rem',

        '--font-family':        "'Sohne', 'Inter', system-ui, sans-serif",
        '--font-family-mono':   "'Roboto Mono', 'Fira Code', monospace",
        '--font-xs':            '0.6875rem',
        '--font-sm':            '0.8125rem',
        '--font-base':          '0.9375rem',
        '--font-lg':            '1.0625rem',
        '--font-xl':            '1.25rem',
        '--font-2xl':           '1.625rem',
        '--font-weight-normal': '400',
        '--font-weight-medium': '500',
        '--font-weight-bold':   '700',

        '--radius-sm':   '4px',
        '--radius-md':   '6px',
        '--radius-lg':   '10px',
        '--radius-full': '9999px',
        '--shadow-sm':   '0 2px 5px rgba(10,37,64,0.06), 0 1px 2px rgba(10,37,64,0.04)',
        '--shadow-md':   '0 4px 14px rgba(10,37,64,0.10), 0 2px 4px rgba(10,37,64,0.06)',
        '--shadow-lg':   '0 15px 35px rgba(10,37,64,0.12), 0 5px 15px rgba(10,37,64,0.08)',
      },
      variants: {
        default: {},
        dark: {
          '--color-bg':              '#1a1a1e',
          '--color-surface':         '#2d2d30',
          '--color-surface-variant': '#3a3a3f',
          '--color-border':          '#4a4a4e',
          '--color-text':            '#f0f0f2',
          '--color-text-secondary':  '#b8b8c0',
          '--color-text-tertiary':   '#80808a',
        },
        warm: {
          '--color-bg':              '#faf7f2',
          '--color-surface':         '#fffcf7',
          '--color-surface-variant': '#f0ebe2',
          '--color-border':          '#dcd8d0',
          '--color-text':            '#0A2540',
          '--color-text-secondary':  '#425466',
          '--color-text-tertiary':   '#8898AA',
        },
        cool: {
          '--color-bg':              '#f2f5fa',
          '--color-surface':         '#f7f9ff',
          '--color-surface-variant': '#eaf0f8',
          '--color-border':          '#d8e0ec',
          '--color-text':            '#0A2540',
          '--color-text-secondary':  '#425466',
          '--color-text-tertiary':   '#8898AA',
        },
        anthro: {
          '--color-bg':              '#FAF6F1',
          '--color-surface':         '#FDF9F5',
          '--color-surface-variant': '#F0E8DC',
          '--color-border':          '#D8C8B4',
          '--color-text':            '#0A2540',
          '--color-text-secondary':  '#425466',
          '--color-text-tertiary':   '#8898AA',
        },
        vibrant: {
          '--color-bg':              '#F6F9FC',
          '--color-surface':         '#FFFFFF',
          '--color-surface-variant': '#EDF2F7',
          '--color-border':          '#D0D8E4',
          '--color-text':            '#000E1A',
          '--color-text-secondary':  '#1A2D40',
          '--color-text-tertiary':   '#607080',
        },
      },
    },

    {
      key: 'neon-ai',
      name: 'Neon AI',
      desc: 'Dark background, vibrant accents, glow effects, dev-tool feel',
      tier: 2,
      tokens: {
        '--color-primary':          '#00E5FF',
        '--color-primary-hover':    '#00B8D4',
        '--color-on-primary':       '#0A0A0F',
        '--color-bg':               '#0A0A0F',
        '--color-surface':          '#13131A',
        '--color-surface-variant':  '#1C1C28',
        '--color-border':           '#2A2A3C',
        '--color-text':             '#E8E8F0',
        '--color-text-secondary':   '#9898B0',
        '--color-text-tertiary':    '#5A5A78',
        '--color-success':          '#00E676',
        '--color-warning':          '#FFD740',
        '--color-danger':           '#FF5252',

        '--space-xs':  '0.25rem',
        '--space-sm':  '0.5rem',
        '--space-md':  '1rem',
        '--space-lg':  '1.5rem',
        '--space-xl':  '2.5rem',

        '--font-family':       "'Inter', system-ui, sans-serif",
        '--font-family-mono':  "'JetBrains Mono', 'Fira Code', 'Cascadia Code', monospace",
        '--font-xs':           '0.6875rem',
        '--font-sm':           '0.8125rem',
        '--font-base':         '0.9375rem',
        '--font-lg':           '1.0625rem',
        '--font-xl':           '1.25rem',
        '--font-2xl':          '1.5rem',
        '--font-weight-normal': '400',
        '--font-weight-medium': '500',
        '--font-weight-bold':   '700',

        '--radius-sm':   '4px',
        '--radius-md':   '8px',
        '--radius-lg':   '12px',
        '--radius-full': '9999px',
        '--shadow-sm':   '0 0 8px rgba(0,229,255,0.15)',
        '--shadow-md':   '0 0 16px rgba(0,229,255,0.20), 0 4px 12px rgba(0,0,0,0.40)',
        '--shadow-lg':   '0 0 32px rgba(0,229,255,0.25), 0 8px 24px rgba(0,0,0,0.60)',
      },
      variants: {
        // default IS dark — no override needed
        default: {},
        // dark is same as default (already dark)
        dark: {},
        warm: {
          '--color-bg':              '#0f0d0a',
          '--color-surface':         '#1a1710',
          '--color-surface-variant': '#242018',
          '--color-border':          '#38321e',
          '--color-text':            '#f0ede8',
          '--color-text-secondary':  '#b0a898',
          '--color-text-tertiary':   '#786a58',
        },
        cool: {
          '--color-bg':              '#080a0f',
          '--color-surface':         '#101318',
          '--color-surface-variant': '#181c24',
          '--color-border':          '#252b38',
          '--color-text':            '#e8ecf0',
          '--color-text-secondary':  '#9098b0',
          '--color-text-tertiary':   '#505a78',
        },
        anthro: {
          '--color-bg':              '#0E0B08',
          '--color-surface':         '#1A1510',
          '--color-surface-variant': '#241E16',
          '--color-border':          '#38301E',
          '--color-text':            '#F0EDE8',
          '--color-text-secondary':  '#B0A898',
          '--color-text-tertiary':   '#786A58',
        },
        vibrant: {
          '--color-bg':              '#050508',
          '--color-surface':         '#0D0D14',
          '--color-surface-variant': '#14141F',
          '--color-border':          '#20203A',
          '--color-text':            '#FFFFFF',
          '--color-text-secondary':  '#C0C0D8',
          '--color-text-tertiary':   '#7070A0',
        },
      },
    },

    {
      key: 'editorial',
      name: 'Editorial',
      desc: 'Serif headings, reading-optimized, strong type hierarchy',
      tier: 2,
      tokens: {
        '--color-primary':          '#1A1A1A',
        '--color-primary-hover':    '#3A3A3A',
        '--color-on-primary':       '#FFFFFF',
        '--color-bg':               '#FAFAF8',
        '--color-surface':          '#FFFFFF',
        '--color-surface-variant':  '#F2F2EE',
        '--color-border':           '#D8D8D0',
        '--color-text':             '#1A1A1A',
        '--color-text-secondary':   '#4A4A45',
        '--color-text-tertiary':    '#8A8A82',
        '--color-success':          '#2E7D32',
        '--color-warning':          '#E65100',
        '--color-danger':           '#C62828',

        '--space-xs':  '0.375rem',
        '--space-sm':  '0.75rem',
        '--space-md':  '1.25rem',
        '--space-lg':  '2rem',
        '--space-xl':  '3.5rem',

        '--font-family':        "Georgia, 'Times New Roman', serif",
        '--font-family-body':   "'Charter', Georgia, serif",
        '--font-xs':            '0.75rem',
        '--font-sm':            '0.875rem',
        '--font-base':          '1.0625rem',
        '--font-lg':            '1.25rem',
        '--font-xl':            '1.5rem',
        '--font-2xl':           '2rem',
        '--font-weight-normal': '400',
        '--font-weight-medium': '500',
        '--font-weight-bold':   '700',

        '--radius-sm':   '2px',
        '--radius-md':   '4px',
        '--radius-lg':   '6px',
        '--radius-full': '9999px',
        '--shadow-sm':   '0 1px 3px rgba(26,26,26,0.08)',
        '--shadow-md':   '0 3px 8px rgba(26,26,26,0.10), 0 1px 3px rgba(26,26,26,0.06)',
        '--shadow-lg':   '0 8px 20px rgba(26,26,26,0.12), 0 3px 8px rgba(26,26,26,0.08)',
      },
      variants: {
        default: {},
        dark: {
          '--color-bg':              '#1a1a1e',
          '--color-surface':         '#2d2d30',
          '--color-surface-variant': '#3a3a3f',
          '--color-border':          '#4a4a4e',
          '--color-text':            '#f0f0f2',
          '--color-text-secondary':  '#b8b8c0',
          '--color-text-tertiary':   '#80808a',
        },
        warm: {
          '--color-bg':              '#faf7f0',
          '--color-surface':         '#fffdf5',
          '--color-surface-variant': '#f5f0e8',
          '--color-border':          '#ddd8cc',
          '--color-text':            '#1A1A1A',
          '--color-text-secondary':  '#4A4A45',
          '--color-text-tertiary':   '#8A8A82',
        },
        cool: {
          '--color-bg':              '#f5f7fa',
          '--color-surface':         '#f9fbff',
          '--color-surface-variant': '#edf0f5',
          '--color-border':          '#d0d4dc',
          '--color-text':            '#1A1A1A',
          '--color-text-secondary':  '#4A4A45',
          '--color-text-tertiary':   '#8A8A82',
        },
        anthro: {
          '--color-bg':              '#FAF6EF',
          '--color-surface':         '#FEFAF4',
          '--color-surface-variant': '#F2EAE0',
          '--color-border':          '#DDD0C0',
          '--color-text':            '#1A1A1A',
          '--color-text-secondary':  '#4A4A45',
          '--color-text-tertiary':   '#8A8A82',
        },
        vibrant: {
          '--color-bg':              '#FAFAF8',
          '--color-surface':         '#FFFFFF',
          '--color-surface-variant': '#F0F0EC',
          '--color-border':          '#C8C8C0',
          '--color-text':            '#000000',
          '--color-text-secondary':  '#2A2A25',
          '--color-text-tertiary':   '#6A6A62',
        },
      },
    },

    {
      key: 'playful',
      name: 'Playful',
      desc: 'Rounded shapes, saturated colors, bouncy consumer feel',
      tier: 2,
      tokens: {
        '--color-primary':          '#6C5CE7',
        '--color-primary-hover':    '#5649C0',
        '--color-on-primary':       '#FFFFFF',
        '--color-bg':               '#FDFCFF',
        '--color-surface':          '#FFFFFF',
        '--color-surface-variant':  '#F0EEFF',
        '--color-border':           '#D8D2F8',
        '--color-text':             '#2D2B55',
        '--color-text-secondary':   '#5A5580',
        '--color-text-tertiary':    '#9990CC',
        '--color-success':          '#00B894',
        '--color-warning':          '#FDCB6E',
        '--color-danger':           '#FF6B6B',

        '--space-xs':  '0.375rem',
        '--space-sm':  '0.75rem',
        '--space-md':  '1.25rem',
        '--space-lg':  '2rem',
        '--space-xl':  '2.5rem',

        '--font-family':        "'Nunito', 'DM Sans', system-ui, sans-serif",
        '--font-xs':            '0.75rem',
        '--font-sm':            '0.875rem',
        '--font-base':          '1rem',
        '--font-lg':            '1.125rem',
        '--font-xl':            '1.375rem',
        '--font-2xl':           '1.75rem',
        '--font-weight-normal': '400',
        '--font-weight-medium': '600',
        '--font-weight-bold':   '800',

        '--radius-sm':   '10px',
        '--radius-md':   '16px',
        '--radius-lg':   '24px',
        '--radius-full': '9999px',
        '--shadow-sm':   '0 2px 8px rgba(108,92,231,0.10)',
        '--shadow-md':   '0 4px 16px rgba(108,92,231,0.15), 0 2px 6px rgba(108,92,231,0.08)',
        '--shadow-lg':   '0 8px 32px rgba(108,92,231,0.20), 0 4px 12px rgba(108,92,231,0.12)',
      },
      variants: {
        default: {},
        dark: {
          '--color-bg':              '#1a1a1e',
          '--color-surface':         '#2d2d30',
          '--color-surface-variant': '#3a3a3f',
          '--color-border':          '#4a4a4e',
          '--color-text':            '#f0f0f2',
          '--color-text-secondary':  '#b8b8c0',
          '--color-text-tertiary':   '#80808a',
        },
        warm: {
          '--color-bg':              '#fdfbf8',
          '--color-surface':         '#fffdf9',
          '--color-surface-variant': '#f5f0ff',
          '--color-border':          '#e0d8f0',
          '--color-text':            '#2D2B55',
          '--color-text-secondary':  '#5A5580',
          '--color-text-tertiary':   '#9990CC',
        },
        cool: {
          '--color-bg':              '#f8f9ff',
          '--color-surface':         '#fafaff',
          '--color-surface-variant': '#eef0ff',
          '--color-border':          '#d8d8f8',
          '--color-text':            '#2D2B55',
          '--color-text-secondary':  '#5A5580',
          '--color-text-tertiary':   '#9990CC',
        },
        anthro: {
          '--color-bg':              '#FAF7F2',
          '--color-surface':         '#FDFAF7',
          '--color-surface-variant': '#F5EEE8',
          '--color-border':          '#E0D4C8',
          '--color-text':            '#2D2B55',
          '--color-text-secondary':  '#5A5580',
          '--color-text-tertiary':   '#9990CC',
        },
        vibrant: {
          '--color-bg':              '#FDFCFF',
          '--color-surface':         '#FFFFFF',
          '--color-surface-variant': '#F5F0FF',
          '--color-border':          '#DDD0FF',
          '--color-text':            '#1A1833',
          '--color-text-secondary':  '#3D3868',
          '--color-text-tertiary':   '#8880CC',
        },
      },
    },

    {
      key: 'minimal-mono',
      name: 'Minimal Mono',
      desc: 'Near-zero color, type weight for hierarchy, ultra-clean',
      tier: 2,
      tokens: {
        '--color-primary':          '#111111',
        '--color-primary-hover':    '#333333',
        '--color-on-primary':       '#FFFFFF',
        '--color-bg':               '#FFFFFF',
        '--color-surface':          '#FAFAFA',
        '--color-surface-variant':  '#F2F2F2',
        '--color-border':           '#DEDEDE',
        '--color-text':             '#111111',
        '--color-text-secondary':   '#444444',
        '--color-text-tertiary':    '#888888',
        '--color-success':          '#111111',
        '--color-warning':          '#111111',
        '--color-danger':           '#111111',

        '--space-xs':  '0.25rem',
        '--space-sm':  '0.5rem',
        '--space-md':  '1rem',
        '--space-lg':  '1.75rem',
        '--space-xl':  '2.5rem',

        '--font-family':       "'DM Mono', 'Fira Mono', 'Courier New', monospace",
        '--font-family-mono':  "'DM Mono', 'Fira Mono', 'Courier New', monospace",
        '--font-xs':           '0.6875rem',
        '--font-sm':           '0.8125rem',
        '--font-base':         '0.9375rem',
        '--font-lg':           '1.0625rem',
        '--font-xl':           '1.25rem',
        '--font-2xl':          '1.5rem',
        '--font-weight-normal': '400',
        '--font-weight-medium': '500',
        '--font-weight-bold':   '700',

        '--radius-sm':   '0px',
        '--radius-md':   '2px',
        '--radius-lg':   '4px',
        '--radius-full': '9999px',
        '--shadow-sm':   '0 1px 2px rgba(0,0,0,0.04)',
        '--shadow-md':   '0 2px 6px rgba(0,0,0,0.06)',
        '--shadow-lg':   '0 4px 12px rgba(0,0,0,0.08)',
      },
      variants: {
        default: {},
        dark: {
          '--color-bg':              '#1a1a1e',
          '--color-surface':         '#2d2d30',
          '--color-surface-variant': '#3a3a3f',
          '--color-border':          '#4a4a4e',
          '--color-text':            '#f0f0f2',
          '--color-text-secondary':  '#b8b8c0',
          '--color-text-tertiary':   '#80808a',
        },
        warm: {
          '--color-bg':              '#fdfaf5',
          '--color-surface':         '#faf7f2',
          '--color-surface-variant': '#f2ede8',
          '--color-border':          '#dedad5',
          '--color-text':            '#111111',
          '--color-text-secondary':  '#444444',
          '--color-text-tertiary':   '#888888',
        },
        cool: {
          '--color-bg':              '#f8f9fc',
          '--color-surface':         '#f5f7fa',
          '--color-surface-variant': '#edf0f5',
          '--color-border':          '#d8dce4',
          '--color-text':            '#111111',
          '--color-text-secondary':  '#444444',
          '--color-text-tertiary':   '#888888',
        },
        anthro: {
          '--color-bg':              '#FAF6F0',
          '--color-surface':         '#F7F2EB',
          '--color-surface-variant': '#EEE6DA',
          '--color-border':          '#D8CCC0',
          '--color-text':            '#111111',
          '--color-text-secondary':  '#444444',
          '--color-text-tertiary':   '#888888',
        },
        vibrant: {
          '--color-bg':              '#FFFFFF',
          '--color-surface':         '#F8F8F8',
          '--color-surface-variant': '#F0F0F0',
          '--color-border':          '#D0D0D0',
          '--color-text':            '#000000',
          '--color-text-secondary':  '#222222',
          '--color-text-tertiary':   '#666666',
        },
      },
    },

  ],

  fontFamilies: {
    system: '-apple-system, BlinkMacSystemFont, system-ui, sans-serif',
    inter:  "'Inter', system-ui, sans-serif",
    serif:  "'Georgia', 'Charter', serif",
    mono:   "'JetBrains Mono', 'Fira Code', monospace",
  },

};
